// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Planner.Data;

#nullable disable

namespace Planner.Migrations
{
    [DbContext(typeof(PlannerContext))]
    [Migration("20231012130813_34")]
    partial class _34
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("Planner.Models.Attractie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Naam")
                        .IsUnique();

                    b.ToTable("Attractie");
                });

            modelBuilder.Entity("Planner.Models.Gast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Gast");
                });

            modelBuilder.Entity("Planner.Models.Reservering", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttractieId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Dag")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DagDeel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GastId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AttractieId");

                    b.HasIndex("GastId");

                    b.ToTable("Reservering", t =>
                        {
                            t.HasCheckConstraint("DagdeelMaximum", "DagDeel <= 35 AND DagDeel >= 0");
                        });
                });

            modelBuilder.Entity("Planner.Models.Reservering", b =>
                {
                    b.HasOne("Planner.Models.Attractie", "Attractie")
                        .WithMany("Reserveringen")
                        .HasForeignKey("AttractieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Planner.Models.Gast", "Gast")
                        .WithMany("Reserveringen")
                        .HasForeignKey("GastId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attractie");

                    b.Navigation("Gast");
                });

            modelBuilder.Entity("Planner.Models.Attractie", b =>
                {
                    b.Navigation("Reserveringen");
                });

            modelBuilder.Entity("Planner.Models.Gast", b =>
                {
                    b.Navigation("Reserveringen");
                });
#pragma warning restore 612, 618
        }
    }
}
